require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec_rails

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Layout/LineLength:
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 20